name: rat-sci-locomotion
channels:
  - conda-forge
  - conda-forge/label/broken
dependencies:
  - python=3.10
  - numpy=1.24.2
  - r-base=4.2.2
  - r-glmmtmb=1.1.5
  - r-lme4=1.1_31
  - r-sjplot
  - r-lmertest
  - r-pbkrtest
  - pip
  - pip:
    - pandas==1.3.5
    - matplotlib==3.5.1
    - scipy==1.9.1
    - seaborn==0.11.2
    - lmfit==1.0.3
    - numdifftools==0.9.40
    - rpy2==3.5.1
    - tables==3.8.0